AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  TrumpTweets:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: TrumpTweets/lambda_function.main_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
  GetTranslation:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: GetTranslation/lambda_function.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
